### ISSUE TITLE
Failure to open file from command-line crashes VisTrails

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1014]
Running on v2.1.4:
```
$ python vistrails\run.py examples\mta-plots-debug.vt
2015-03-16 15:39:33,891 CRITICAL:
C:\programmation\vistrails\dat\vistrails\vistrails\core\application.py, line 678
VistrailsDBException: This vistrail was created by a newer version of VisTrails and cannot be opened.
Traceback (most recent call last):
  File "C:\programmation\vistrails\dat\vistrails\vistrails\core\application.py", line 657, in open_vistrail
    loaded_objs = vistrails.core.db.io.load_vistrail(locator, False)
  File "C:\programmation\vistrails\dat\vistrails\vistrails\core\db\io.py", line 75, in load_vistrail
    res = locator.load()
  File "C:\programmation\vistrails\dat\vistrails\vistrails\core\db\locator.py", line 488, in load
    save_bundle = _ZIPFileLocator.load(self, klass.vtType)
  File "C:\programmation\vistrails\dat\vistrails\vistrails\db\services\locator.py", line 650, in load
    (save_bundle, tmp_dir) = io.open_bundle_from_zip_xml(type, self._name)
  File "C:\programmation\vistrails\dat\vistrails\vistrails\db\services\io.py", line 580, in open_bundle_from_zip_xml
    return open_vistrail_bundle_from_zip_xml(filename)
  File "C:\programmation\vistrails\dat\vistrails\vistrails\db\services\io.py", line 735, in open_vistrail_bundle_from_zip_xml
    vistrail = open_vistrail_from_xml(os.path.join(root, fname))
  File "C:\programmation\vistrails\dat\vistrails\vistrails\db\services\io.py", line 699, in open_vistrail_from_xml
    raise VistrailsDBException(msg)
VistrailsDBException: VistrailsDBException: This vistrail was created by a newer version of VisTrails and cannot be opened.

Uncaught exception on initialization: 'NoneType' object has no attribute 'controller'
Traceback (most recent call last):
  File "vistrails\run.py", line 123, in <module>
    v = vistrails.gui.application.start_application()
  File "C:\programmation\vistrails\dat\vistrails\vistrails\gui\application.py", line 845, in start_application
    x = VistrailsApplication.init(optionsDict)
  File "C:\programmation\vistrails\dat\vistrails\vistrails\gui\application.py", line 226, in init
    self.interactiveMode()
  File "C:\programmation\vistrails\dat\vistrails\vistrails\gui\application.py", line 435, in interactiveMode
    self.process_interactive_input()
  File "C:\programmation\vistrails\dat\vistrails\vistrails\core\application.py", line 532, in process_interactive_input
    mashupVersion=mashupversion)
  File "C:\programmation\vistrails\dat\vistrails\vistrails\gui\vistrails_window.py", line 1747, in open_vistrail_without_prompt
    view = self.open_vistrail(locator, version, is_abstraction)
  File "C:\programmation\vistrails\dat\vistrails\vistrails\gui\vistrails_window.py", line 1642, in open_vistrail
    view.is_abstraction = view.controller.is_abstraction
AttributeError: 'NoneType' object has no attribute 'controller'
```
Then VisTrails closes, there isn't even time to read the error messagebox.

**Comment by remram44** [comment]
It appears that I have already fixed this with 377b80cf.
