### ISSUE TITLE
corie.xml doesn't open

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1025]
corie.xml is missing a module, but instead of seeing an `InvalidPipeline`, I get a traceback and the file doesn't get opened.

```
Cannot find id: [('module', 33L), ('function', 0L)]
Cannot find id: [('module', 50L), ('function', 0L)]
Cannot find id: [('module', 50L), ('function', 1L)]
Cannot find id: [('module', 50L), ('function', 0L)]
Cannot find id: [('module', 52L), ('portSpec', ('points', 'input'))]
Cannot find id: [('module', 45L), ('function', 0L)]
Cannot find id: [('module', 33L), ('function', 0L)]
Cannot find id: [('module', 58L), ('function', 1L)]
Cannot find id: [('module', 57L), ('function', 0L)]
Cannot find id: [('module', 58L), ('function', 2L)]
Cannot find id: [('module', 59L), ('function', 1L)]
Cannot find id: [('module', 67L), ('function', 0L)]
Cannot find id: [('module', 65L), ('portSpec', ('ugrid', 'output'))]
Cannot find id: [('module', 75L), ('function', 0L)]
Cannot find id: [('module', 75L), ('function', 1L)]
Cannot find id: [('module', 68L), ('function', 2L)]
Cannot find id: [('module', 16L), ('function', 0L)]
Cannot find id: [('module', 73L), ('function', 1L)]
Cannot find id: [('module', 80L), ('function', 0L)]
Cannot find id: [('module', 73L), ('function', 1L)]
Cannot find id: [('module', 86L), ('portSpec', ('polydata', 'input'))]
Cannot find id: [('module', 91L), ('portSpec', ('sgrid', 'output'))]
Cannot find id: [('module', 93L), ('function', 0L)]
Cannot find id: [('module', 119L), ('portSpec', ('value', 'output'))]
Cannot find id: [('module', 120L), ('portSpec', ('value', 'output'))]
Cannot find id: [('module', 16L), ('function', 0L)]
Cannot find id: [('module', 0L), ('portSpec', ('polyline', 'output'))]
Cannot find id: [('module', 7L), ('portSpec', ('value', 'output'))]
Cannot find id: [('module', 10L), ('portSpec', ('value', 'output'))]
Cannot find id: [('module', 11L), ('portSpec', ('value', 'output'))]
Cannot find id: [('module', 12L), ('portSpec', ('value', 'output'))]
Cannot find id: [('module', 17L), ('function', 0L)]
Cannot find id: [('module', 15L), ('function', 0L)]
Cannot find id: [('module', 20L), ('portSpec', ('value', 'output'))]
Traceback (most recent call last):
  File "vistrails/gui/vistrails_window.py", line 1788, in open_vistrail_default
    self.open_vistrail_from_locator(FileLocator())
  File "vistrails/gui/vistrails_window.py", line 1661, in open_vistrail_from_locator
    execute_workflow=execute)
  File "vistrails/gui/vistrails_window.py", line 1730, in open_vistrail_without_prompt
    view = self.open_vistrail(locator, version, is_abstraction)
  File "vistrails/gui/vistrails_window.py", line 1619, in open_vistrail
    is_abstraction):
  File "vistrails/core/application.py", line 408, in open_vistrail
    loaded_objs = vistrails.core.db.io.load_vistrail(locator, False)
  File "vistrails/core/db/io.py", line 78, in load_vistrail
    res = locator.load()
  File "vistrails/core/db/locator.py", line 132, in load
    obj = _XMLFileLocator.load(self, klass.vtType)
  File "vistrails/db/services/locator.py", line 501, in load
    obj = io.open_from_xml(self._name, type)
  File "vistrails/db/services/io.py", line 548, in open_from_xml
    return open_vistrail_from_xml(filename)
  File "vistrails/db/services/io.py", line 693, in open_vistrail_from_xml
    vistrail = translate_vistrail(vistrail, version)
  File "vistrails/db/versions/__init__.py", line 149, in translate_vistrail
    target_version)
  File "vistrails/db/versions/__init__.py", line 136, in translate_object
    obj = getattr(translate_module, method_name)(obj)
  File "vistrails/db/versions/v0_7_0/translate/v0_6_0.py", line 51, in translateVistrail
    op.db_parentObjId)
  File "vistrails/db/versions/v0_7_0/translate/v0_6_0.py", line 162, in convert_data
    descriptor = registry.get_descriptor_from_name_only(child.db_name)
  File "vistrails/core/modules/module_registry.py", line 870, in get_descriptor_from_name_only
    raise MissingModule("<unknown package>", name, None)
vistrails.core.modules.module_registry.MissingModule: Missing module vtkCORIEUnstructuredGridReader in package <unknown package>
```

**Comment by dakoop** [comment]
This was a specialized VTK module that was developed during the CORIE project. I'm not sure where this is now and if the functionality may have been merged into VTK at some point.

**Comment by remram44** [comment]
This happens because of upgrade from schema 0.7.0. Not super important to fix, but it'll be nice at least to catch the error and display something, at best to go through with the upgrade and get to InvalidPipeline.
