### ISSUE TITLE
Upgrades to new VTK package

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1041]
It seems that some VTK examples don't upgrade correctly after 1b024ce5 (fix for #1021); for instance, `vtk_examples/ImageProcessing/Coutours2D.vt`: the vtkRenderer module fails. Messages:
```
Traceback (most recent call last):
  File "vistrails/core/vistrail/controller.py", line 3216, in process_package_exceptions
    self, err._module_id, pipeline)
  File "vistrails/core/upgradeworkflow.py", line 235, in dispatch_request
    return f(controller, module_id, current_pipeline)
  File "vistrails/packages/vtk/init.py", line 585, in handle_module_upgrade_request
    _remap)
  File "vistrails/core/upgradeworkflow.py", line 802, in remap_module
    use_registry)
  File "vistrails/core/upgradeworkflow.py", line 687, in replace_module
    use_registry)
  File "vistrails/core/upgradeworkflow.py", line 547, in replace_generic
    function_ops.extend(remap(function, new_module))
  File "vistrails/packages/vtk/init.py", line 288, in remap
    port_spec = reg.get_input_port_spec(new_module, port_name)
  File "vistrails/core/modules/module_registry.py", line 1985, in get_input_port_spec
    descriptor = module.module_descriptor
  File "vistrails/core/vistrail/module.py", line 262, in _get_module_descriptor
    weakref.ref(reg.get_descriptor_by_name(*self.descriptor_info))
  File "vistrails/core/modules/module_registry.py", line 767, in get_descriptor_by_name
    raise MissingPackageVersion(identifier, package_version)
MissingPackageVersion: Missing version 0.9.3 of package edu.utah.sci.vistrails.vtk
2015-04-02 10:54:03,075 CRITICAL:
vistrails/gui/vistrail_controller.py, line 566
Error changing version
InvalidPipeline: Pipeline has errors. Please see the detailed message for more information.
  Missing version 0 of package edu.utah.sci.vistrails.vtk
  Missing version 0.9.3 of package edu.utah.sci.vistrails.vtk
```

**Comment by rexissimus** [comment]
66e8ca7bd2d79a97281f2386f182efdf1820b1ad fixes this by always using the latest package version when fetching port specs and creating functions.

cc @dakoop

It seems like there is no way to create a function for intermediate versions in the upgrade. This worked before because the version check did not work and the current descriptor version was always returned.

    File "vistrails/core/vistrail/controller.py", line 784, in create_function
    File "vistrails/core/vistrail/controller.py", line 790, in create_function_static
    File "/vistrails/core/vistrail/module.py", line 288, in get_port_spec
    File "vistrails/core/vistrail/module.py", line 262, in _get_module_descriptor
    File "vistrails/core/modules/module_registry.py", line 767, in get_descriptor_by_name
    MissingPackageVersion: Missing version 0.9.3 of package edu.utah.sci.vistrails.vtk
