### ISSUE TITLE
Can't query across upgrades

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1054]
Trying a visual query shows a traceback:
```
Traceback (most recent call last):
  File "C:\Program Files\VisTrails 2.2-pre-17\vistrails\gui\vistrails_window.py", line 1937, in method
    getattr(obj, method_name)()
  File "C:\Program Files\VisTrails 2.2-pre-17\vistrails\gui\vistrail_view.py", line 1087, in execute
    view.execute()
  File "C:\Program Files\VisTrails 2.2-pre-17\vistrails\gui\query_view.py", line 263, in execute
    self.query_controller.run_search(None)
  File "C:\Program Files\VisTrails 2.2-pre-17\vistrails\gui\query_view.py", line 149, in run_search
    result_entities = do_search(True)
  File "C:\Program Files\VisTrails 2.2-pre-17\vistrails\gui\query_view.py", line 145, in do_search
    self.search.run()
  File "C:\Program Files\VisTrails 2.2-pre-17\vistrails\core\query\multiple.py", line 60, in run
    query.run(entity.vistrail, '')
  File "C:\Program Files\VisTrails 2.2-pre-17\vistrails\core\query\combined.py", line 49, in run
    VisualQuery.run(self, vistrail, name)
  File "C:\Program Files\VisTrails 2.2-pre-17\vistrails\core\query\visual.py", line 94, in run
    p = vistrail.getPipeline(version)
  File "C:\Program Files\VisTrails 2.2-pre-17\vistrails\core\vistrail\vistrail.py", line 311, in getPipeline
    raise InvalidPipeline([e])
vistrails.core.utils.InvalidPipeline: Pipeline has errors. Please see the detailed message for more information.
  Illegal change operation: 1247
```

**Comment by remram44** [comment]
I think this will happen whenever the vistrail has any upgrade. `getPipeline()` is not a safe operation.

**Comment by dakoop** [comment]
Yeah, should we deprecate `getPipeline`? I don't know if there is any current way to materialize any given pipeline without allowing significant controller interaction.

**Comment by remram44** [comment]
Looking at `do_version_switch()`, it looks like a method could be introduced to get a pipeline while going through the upgrading, without actually changing the `current_version`/`current_pipeline` or mutating the controller in any way (apart from the pipeline cache). Perhaps such a method could replace the current calls to `getPipeline()`?

**Comment by rexissimus** [comment]
Queries now use upgraded pipelines if ``hideUpgrades`` is set, creating new upgrades when required. If ``hideUpgrades`` is not set the query will still run on the original pipeline.
