### ISSUE TITLE
Upgrades break loading single pipeline

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1074]
Took me a while, but this is what I have: apparently the upgrade can happen between the add_new_action() and perform_action() calls to the controller, because the add_new_action() overloaded in the GUI controller emits stateChanged() which can synchronously make observers call change_selected_version (example: `QQueryView#update_controller()`).

Then weird stuff happens, process_package_exceptions() end up performing the action twice, and Pipeline#add_module() raises `VisTrailsInternalError("duplicate module id: m.id")`

Happens if you load any pipeline from XML which requires an upgrade.

**Comment by remram44** [comment]
```
add_module(0)
add_module(1)
INFO:VisLog:/home/remram/Documents/programming/dat/vistrails/vistrails/core/vistrail/controller.py, line 3185
Processing upgrades in package "org.vistrails.vistrails.basic"
MissingPackageVersion: Missing version 2.1 of package org.vistrails.vistrails.basic

MissingPackageVersion: Missing version 2.1 of package org.vistrails.vistrails.basic

Traceback (most recent call last):
  File "/home/remram/Documents/programming/dat/vistrails/vistrails/core/vistrail/controller.py", line 3227, in process_package_exceptions
add_module(0)
    pipeline.perform_action(action)
  File "/home/remram/Documents/programming/dat/vistrails/vistrails/core/vistrail/pipeline.py", line 375, in perform_action
    self.perform_operation(operation)
  File "/home/remram/Documents/programming/dat/vistrails/vistrails/core/vistrail/pipeline.py", line 400, in perform_operation
    f(op.data, op.parentObjType, op.parentObjId)
  File "/home/remram/Documents/programming/dat/vistrails/vistrails/core/vistrail/pipeline.py", line 413, in add_module
    raise VistrailsInternalError("duplicate module id: %d" % m.id )
VistrailsInternalError: Vistrails Internal Error: duplicate module id: 0
add_module(1)
add_module(0)
add_module(1)
INFO:VisLog:/home/remram/Documents/programming/dat/vistrails/vistrails/core/vistrail/controller.py, line 3185
Processing upgrades in package "org.vistrails.vistrails.basic"
MissingPackageVersion: Missing version 2.1 of package org.vistrails.vistrails.basic

MissingPackageVersion: Missing version 2.1 of package org.vistrails.vistrails.basic

add_module(2)
add_module(3)
add_module(0)
add_module(1)
INFO:VisLog:/home/remram/Documents/programming/dat/vistrails/vistrails/core/vistrail/controller.py, line 3185
Processing upgrades in package "org.vistrails.vistrails.basic"
MissingPackageVersion: Missing version 2.1 of package org.vistrails.vistrails.basic

MissingPackageVersion: Missing version 2.1 of package org.vistrails.vistrails.basic

add_module(4)
add_module(5)
```

Not sure about the right way to fix this.

**Comment by remram44** [comment]
Adding tag *gui* because this is caused by the signal-sending override of `set_changed()`
