### ISSUE TITLE
Missing module prevents displaying a pipeline

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1078]
It looks like something is not caught somewhere. Instead of displaying an invalid pipeline the usual way, if a module name isn't known, it is impossible to switch to the version at all.

Affects 2.1 and 2.2.
```
2015-05-22 16:04:49,918 CRITICAL:
vistrails/gui/vistrail_controller.py, line 616
Unexpected Exception
Traceback (most recent call last):
  File "vistrails/run.py", line 163, in <module>
    main()
  File "vistrails/run.py", line 157, in main
    v = app.exec_()
  File "vistrails/gui/collection/workspace.py", line 927, in item_selected
    open_vistrail(locator, **args)
  File "vistrails/gui/vistrails_window.py", line 1730, in open_vistrail_without_prompt
    view = self.open_vistrail(locator, version, is_abstraction)
  File "vistrails/gui/vistrails_window.py", line 1619, in open_vistrail
    is_abstraction):
  File "vistrails/core/application.py", line 435, in open_vistrail
    controller.select_latest_version()
  File "vistrails/core/vistrail/controller.py", line 3121, in select_latest_version
    self.change_selected_version(self.get_latest_version_in_graph())
--- Exception caught here ---
  File "vistrails/gui/vistrail_controller.py", line 553, in change_selected_version
    do_validate, from_root)
  File "vistrails/core/vistrail/controller.py", line 3782, in do_version_switch
    report_all_errors)
  File "vistrails/core/vistrail/controller.py", line 3522, in handle_invalid_pipeline
    cur_pipeline)
  File "vistrails/core/vistrail/controller.py", line 3406, in process_package_exceptions
    self, pipeline, old_module.id, new_pipeline)
  File "vistrails/core/upgradeworkflow.py", line 675, in replace_group
    old_group, new_group)
  File "vistrails/core/upgradeworkflow.py", line 630, in replace_generic
    old_conn.destination)
  File "vistrails/core/upgradeworkflow.py", line 427, in create_new_connection
    output_port_spec = src_module.get_port_spec(src_port, 'output')
  File "vistrails/core/vistrail/module.py", line 288, in get_port_spec
    if self.has_portSpec_with_name((port_name, port_type)):
  File "vistrails/core/vistrail/group.py", line 173, in has_portSpec_with_name
    self.make_port_specs()
  File "vistrails/core/vistrail/group.py", line 239, in make_port_specs
    self.get_port_spec_info(module)
  File "vistrails/core/vistrail/group.py", line 215, in get_port_spec_info
    module)
  File "vistrails/core/modules/sub_module.py", line 323, in get_port_spec_info
    sigstring, depth = coalesce_port_specs(neighbors, type)
  File "vistrails/core/modules/sub_module.py", line 267, in coalesce_port_specs
    cur_descs = port_spec.descriptors()
  File "vistrails/core/vistrail/port_spec.py", line 274, in descriptors
    return [i.descriptor for i in self.port_spec_items]
  File "vistrails/core/vistrail/port_spec_item.py", line 185, in _get_descriptor
    self.namespace)
  File "vistrails/core/modules/module_registry.py", line 772, in get_descriptor_by_name
    package_version)
MissingModule: Missing module NumPyArray in package edu.utah.sci.vistrails.matplotlib
```

**Comment by remram44** [comment]
Looks to be related somehow to the upgrade logic (or submodules?)

**Comment by remram44** [comment]
File is [histogram.xml from DAT](https://github.com/VisTrails/VisTrails/blob/1a1f08d08a613de3b7464fe454f3b1e99341b173/vistrails/packages/matplotlib/dat-plots/histogram.xml)

**Comment by dakoop** [comment]
(I haven't looked at the file yet.) This is probably related to the fact that upgrades are done module-by-module. That means after each upgrade, we need to construct connections from the updated module back to the rest of the pipeline. If there are two connected modules to be updated, the first is updated and may need to connect back to an invalid module which means the connection cannot be properly instantiated (meaning one port is not linked back to a valid port spec). There is code that is supposed to avoid this, but perhaps other changes have complicated it? Is the module in question a group or subworkflow?

**Comment by remram44** [comment]
There is indeed a Group involved.
