### ISSUE TITLE
Traceback on diff

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#1080]
I get this everytime, comparing versions 28 and 36 of [this file](https://gist.github.com/remram44/bde203c029b28c647d75):
```
Traceback (most recent call last):
  File "/home/remram/Documents/programming/dat/vistrails/vistrails/gui/vistrail_view.py", line 871, in diff_requested
    view.set_diff(version_a, version_b, vistrail_b)
  File "/home/remram/Documents/programming/dat/vistrails/vistrails/gui/vis_diff.py", line 557, in set_diff
    self.diff = vistrails.core.db.io.get_workflow_diff(*self.diff_versions)
  File "/home/remram/Documents/programming/dat/vistrails/vistrails/core/db/io.py", line 134, in get_workflow_diff
    True)
  File "/home/remram/Documents/programming/dat/vistrails/vistrails/db/services/vistrail.py", line 1528, in getWorkflowDiff
    return getWorkflowDiffCommon(vistrail_1, v_1, v_2, heuristic_match)
  File "/home/remram/Documents/programming/dat/vistrails/vistrails/db/services/vistrail.py", line 1429, in getWorkflowDiffCommon
    True, heuristic_match)
  File "/home/remram/Documents/programming/dat/vistrails/vistrails/db/services/vistrail.py", line 1506, in check_params_diff
    moduleParamChanges = getParamChanges(m1, m2, same_vt, heuristic_match)
  File "/home/remram/Documents/programming/dat/vistrails/vistrails/db/services/vistrail.py", line 1014, in getParamChanges
    m2_functions = m2.db_get_functions()
AttributeError: 'NoneType' object has no attribute 'db_get_functions'
```

**Comment by remram44** [comment]
I can't pretend to understand all that goes on in the diff logic, but [these lines](https://github.com/VisTrails/VisTrails/blob/9ff0d5d07ef5cf422457d69aba3da5b58b74982c/vistrails/db/services/vistrail.py#L1409-L1411) are definitely suspicious: the old module id is used twice, but that might not resolve in the new workflow. Please check.

@dakoop: Commit message for 5d34e93e states that "ids are now unique" but that doesn't seem to be the case.

**Comment by dakoop** [comment]
If a module is designated as only having parameter changes, control parameter changes, or annotation changes, the module itself does not change and should be the same id in both versions.

**Comment by dakoop** [comment]
Got it. When support for annotations and control parameters in the diff was added to the diff in 64a77598, it did not mirror what was done for standard parameters exactly. Specifically, deleting from the corresponding dictionary was not done if the module was deleted like it was for parameters.

**Comment by remram44** [comment]
Awesome, thanks!

**Comment by rexissimus** [comment]
Backported to v2.2 with 0f0417e3d79a3df3d6bf2d3cde58b3178a2ed095.
