### ISSUE TITLE
alps initialization failed

### ISSUE THREAD

**Issue by irisre** [VisTrails/VisTrails#1193]
Hi,
I have installed ALPS 2.2,  VisTrails 2.1.5 and the ALPS VisTrails module. I cannot enable the alps package since initialization fails. I saw a similar question here: https://github.com/VisTrails/VisTrails/issues/13, but there is not a previous version I can use in the download page. Any help would be highly appreciated. 
The error message is below:

```
CRITICAL
2016-08-30 15:21:01,213
C:\Program Files\VisTrails\vistrails\gui\preferences.py, line 326
Initialization of package 'alps' failed
InitializationFailed: Package 'ALPS' failed to initialize because of the following exceptions:
Traceback (most recent call last):
  File "C:\Program Files\VisTrails\vistrails\core\modules\module_registry.py", line 1635, in initialize_package
    package.initialize()
  File "C:\Program Files\VisTrails\vistrails\core\modules\package.py", line 427, in initialize
    __import__(name, globals(), locals(), [])
  File "C:\Program Files\VisTrails\vistrails\core\packagemanager.py", line 259, in _import_override
    package_importing_directly=False)
  File "C:\Program Files\VisTrails\vistrails\core\modules\package.py", line 309, in import_override
    res = orig_import(name, globals, locals, fromlist, level)
  File "C:\Program Files\VisTrails\vistrails\packages\alps\init.py", line 22, in <module>
    import applications
  File "C:\Program Files\VisTrails\vistrails\core\packagemanager.py", line 250, in _import_override
    package_importing_directly=True)
  File "C:\Program Files\VisTrails\vistrails\core\modules\package.py", line 309, in import_override
    res = orig_import(name, globals, locals, fromlist, level)
  File "C:\Program Files\VisTrails\vistrails\packages\alps\applications.py", line 19, in <module>
    import tools
  File "C:\Program Files\VisTrails\vistrails\core\packagemanager.py", line 250, in _import_override
    package_importing_directly=True)
  File "C:\Program Files\VisTrails\vistrails\core\modules\package.py", line 309, in import_override
    res = orig_import(name, globals, locals, fromlist, level)
  File "C:\Program Files\VisTrails\vistrails\packages\alps\tools.py", line 18, in <module>
    from packages.HTTP.init import HTTPFile
  File "C:\Program Files\VisTrails\vistrails\core\packagemanager.py", line 250, in _import_override
    package_importing_directly=True)
  File "C:\Program Files\VisTrails\vistrails\core\modules\package.py", line 330, in import_override
    res = orig_import(name, globals, locals, fromlist, level)
ImportError: No module named HTTP.init
```

**Comment by remram44** [comment]
Hi,

The line numbers in your traceback don't seem to match with VisTrails 2.1.5, but rather 2.2. Are you sure you grabbed the right version?

ALPS looks like it hasn't been updated for VisTrails 2.2, in particular replacing HTTP with the URL package.

**Comment by irisre** [comment]
Thanks for your answer. Probably not... I installed it on a different computer and it seems fine so far.
