### ISSUE TITLE
QGIS package error load

### ISSUE THREAD

**Issue by samtux** [VisTrails/VisTrails#1200]
I get the next error when qgis pacage load:

```
Critical message:
Initialization of package 'qgis' failed

 
InitializationFailed: Package 'QGIS' failed to initialize because of the following exceptions:
Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/vistrails/core/modules/module_registry.py", line 1635, in initialize_package
package.initialize()
File "/usr/lib/python2.7/site-packages/vistrails/core/modules/package.py", line 429, in initialize
__import__(name, globals(), locals(), [])
File "/usr/lib/python2.7/site-packages/vistrails/core/packagemanager.py", line 266, in _import_override
package_importing_directly=False)
File "/usr/lib/python2.7/site-packages/vistrails/core/modules/package.py", line 310, in import_override
res = orig_import(name, globals, locals, fromlist, level)
File "/usr/lib/python2.7/site-packages/vistrails/packages/qgis/init.py", line 43, in <module>
import qgis.core
File "/usr/lib/python2.7/site-packages/vistrails/core/packagemanager.py", line 257, in _import_override
package_importing_directly=True)
File "/usr/lib/python2.7/site-packages/vistrails/core/modules/package.py", line 310, in import_override
res = orig_import(name, globals, locals, fromlist, level)
File "/usr/share/qgis/python/qgis/__init__.py", line 26, in <module>
from qgis.PyQt import QtCore
File "/usr/lib/python2.7/site-packages/vistrails/core/packagemanager.py", line 266, in _import_override
package_importing_directly=False)
File "/usr/lib/python2.7/site-packages/vistrails/core/modules/package.py", line 310, in import_override
res = orig_import(name, globals, locals, fromlist, level)
File "/usr/share/qgis/python/qgis/PyQt/QtCore.py", line 28, in <module>
sip.setapi(api, 2)
ValueError: API 'QDate' has already been set to version 1
 
 
Time:
2016-11-14 12:10:53,124
Location:
/usr/lib/python2.7/site-packages/vistrails/gui/preferences.py, line 326

```

**Comment by remram44** [comment]
It doesn't look like you are running the VisTrails GUI, is that so?

It looks like this was caused by QGIS now trying to set the PyQt API version while we already imported it. Can you try changing the order of the lines in `/usr/lib/python2.7/site-packages/vistrails/packages/qgis/init.py` so that `from PyQt4 import QtCore, QtGui` comes after the other `import` lines, like so:

```python
from __future__ import division

#from PyQt4 import QtCore, QtGui  # Move from here
from vistrails.core.modules.vistrails_module import Module
from vistrails.packages.spreadsheet.basic_widgets import SpreadsheetCell
from vistrails.packages.spreadsheet.spreadsheet_cell import QCellWidget

import qgis.core
import qgis.gui

import itertools
import os

from PyQt4 import QtCore, QtGui  # Move to here
```
