### ISSUE TITLE
brain_script.py example doesn't work

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#874]
The spreadsheet isn't available because the GUI is not running:

```
2014-07-11 14:47:04,803 CRITICAL:
../..\vistrails\core\packagemanager.py, line 668
Initialization of package <codepath spreadsheet> failed and will be disabled
InitializationFailed: Package 'VisTrails Spreadsheet' failed to initialize because of the following exceptions:
Traceback (most recent call last):
  File "../..\vistrails\core\modules\module_registry.py", line 1634, in initialize_package
    package.initialize()
  File "../..\vistrails\core\modules\package.py", line 454, in initialize
    self._init_module.initialize()
  File "../..\vistrails\packages\spreadsheet\init.py", line 114, in initialize
    raise RuntimeError, "GUI is not running. The Spreadsheet package requires the GUI"
RuntimeError: GUI is not running. The Spreadsheet package requires the GUI
```

(note that even if I run a script that doesn't use the GUI, I'll see that, because it loads all the packages in the startup XML. For the same reason, I might need to open !VisTrails and enable needed packages before running the script)

```
Traceback (most recent call last):
  File "brain_script.py", line 107, in <module>
    renderer, 'Instance')
  File "../..\vistrails\core\api.py", line 324, in add_and_connect_module
    module = self.controller.create_module(identifier, name, **kwargs)
  File "../..\vistrails\core\vistrail\controller.py", line 648, in create_module
    return self.create_module_static(self.id_scope, *args, **kwargs)
  File "../..\vistrails\core\vistrail\controller.py", line 654, in create_module_static
    d = reg.get_descriptor_by_name(identifier, name, namespace)
  File "../..\vistrails\core\modules\module_registry.py", line 797, in get_descriptor_by_name
    package_version)
vistrails.core.modules.module_registry.MissingModule: Missing module VTKCell in package edu.utah.sci.vistrails.vtk
```

Affects v2.1.

**Comment by remram44** [comment]
2cf6f4ef removes `examples/scripting/` since these don't work and are replaced with the new API which is a much nicer option.
