### ISSUE TITLE
Errors are not quoted properly in XML log

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#917]
```
Traceback (most recent call last):
  File "vistrails/gui/collection/workspace.py", line 924, in item_selected
    open_vistrail(locator, **args)
  File "vistrails/gui/vistrails_window.py", line 1764, in open_vistrail_without_prompt
    view = self.open_vistrail(locator, version, is_abstraction)
  File "vistrails/gui/vistrails_window.py", line 1653, in open_vistrail
    is_abstraction):
  File "vistrails/core/application.py", line 408, in open_vistrail
    *loaded_objs[1:])
  File "vistrails/gui/application.py", line 307, in add_vistrail
    return self.builderWindow.add_vistrail(*objs)
  File "vistrails/gui/vistrails_window.py", line 1613, in add_vistrail
    view = self.create_view(*objs)
  File "vistrails/gui/vistrails_window.py", line 947, in create_view
    thumbnail_files, mashups)
  File "vistrails/gui/vistrail_view.py", line 123, in __init__
    self.set_controller(self.controller)
  File "vistrails/gui/vistrail_view.py", line 202, in set_controller
    view.set_controller(controller)
  File "vistrails/gui/collection/vis_log.py", line 460, in set_controller
    for e in self.controller.read_log().workflow_execs:
  File "vistrails/core/vistrail/controller.py", line 3817, in read_log
    return self.vistrail.get_persisted_log()
  File "vistrails/core/vistrail/vistrail.py", line 1034, in get_persisted_log
    log = open_log_from_xml(self.db_log_filename, True)
  File "vistrails/db/services/io.py", line 1196, in open_log_from_xml
    parser.feed(f.read())
cElementTree.ParseError: not well-formed (invalid token): line 254, column 81
```

Looking at the XML file, there are `\x01` bytes in there. They should be escaped in XML.

**Comment by remram44** [comment]
Can't reproduce right now
