### ISSUE TITLE
Exception when opening a vistrail

### ISSUE THREAD

**Issue by remram44** [VisTrails/VisTrails#918]
Doesn't happen everytime, unfortunately. Might have to do with the order in which notifications are sent, when the new controller is loaded.

As far as I understand it, in response to the "controller changed" notification, the version view might emit a "version changed" notification. This is super-unsafe since not every observer has changed to the new controller yet.

```
!!!!!!!!!!
Got unexpected exception, starting debugger
Traceback (most recent call last):
  File "vistrails/run.py", line 160, in <module>
    main()
  File "vistrails/run.py", line 154, in main
    v = app.exec_()
  File "vistrails/gui/vistrails_window.py", line 1491, in new_vistrail
    self.open_vistrail(locator)
  File "vistrails/gui/vistrails_window.py", line 1628, in open_vistrail
    is_abstraction):
  File "vistrails/core/application.py", line 407, in open_vistrail
    *loaded_objs[1:])
  File "vistrails/gui/application.py", line 307, in add_vistrail
    return self.builderWindow.add_vistrail(*objs)
  File "vistrails/gui/vistrails_window.py", line 1588, in add_vistrail
    view = self.create_view(*objs)
  File "vistrails/gui/vistrails_window.py", line 947, in create_view
    thumbnail_files, mashups)
  File "vistrails/gui/vistrail_view.py", line 123, in __init__
    self.set_controller(self.controller)
  File "vistrails/gui/vistrail_view.py", line 202, in set_controller
    view.set_controller(controller)
  File "vistrails/gui/version_view.py", line 1282, in set_controller
    self.scene().setupScene(controller)
  File "vistrails/gui/version_view.py", line 1019, in setupScene
    self.selectionChanged()
  File "vistrails/gui/version_view.py", line 1137, in selectionChanged
    -1, self.select_by_click, True, False, False)
  File "vistrails/gui/vistrail_view.py", line 840, in version_selected
    _app.notify("pipeline_changed", self.controller.current_pipeline)
  File "vistrails/gui/vistrails_window.py", line 1271, in notify
    vt_app.send_notification(notification_id, *args)
--- Exception caught here ---
  File "vistrails/gui/application.py", line 404, in send_notification
    m(*args)
  File "vistrails/gui/paramexplore/param_view.py", line 122, in set_pipeline
    self.pipeline_view.scene().setupScene(pipeline)
  File "vistrails/gui/pipeline_view.py", line 2346, in setupScene
    self.update_connections()
  File "vistrails/gui/pipeline_view.py", line 2756, in update_connections
    if self.controller.current_pipeline.is_valid:
AttributeError: 'NoneType' object has no attribute 'is_valid'
!!!!!!!!!!
> vistrails/gui/pipeline_view.py(2756)update_connections()
-> if self.controller.current_pipeline.is_valid:
(Pdb) p self.controller.current_pipeline
None
(Pdb)
```

I'm not sure if this affects other versions, bisecting is hard since it doesn't happen all the time.

(also, note the traceback & debugger integration)

**Comment by remram44** [comment]
I still run into this

**Comment by rexissimus** [comment]
397af1a667e5848b5322d752f84801e1fed88dcc removes the error. But this is not the actual problem. It looks like setupScene is causing a signal that is setting current_pipeline to None. This is happening in the Parameter Exploration view. All the views are updated when the pipeline changes so there are a lot of signals being sent around. Most views are hardened by only updating when something have really changed. We should improve this, but it will be a major change.
